"""Topic-specific questions; ten foundations, ten applications, ten advanced tasks per day."""
QUESTIONS = {
1: [
"What problem does PySpark solve when retail data outgrows one computer?",
"What is a SparkSession, and how do you create one?",
"What does local[2] mean in the supplied setup?",
"What is the driver's role in a Spark application?",
"What work is performed by executors?",
"What is a DataFrame, and what does its schema describe?",
"How do transformations differ from actions?",
"Why does constructing a filter not immediately read every row?",
"How do you display five orders without collecting the whole table?",
"How do you stop a SparkSession after an assignment?",
"Read orders.csv and verify its row count against the manifest.",
"Print the order schema and identify columns read as strings.",
"Select order_id, customer_id, and status and display ten rows.",
"Filter orders from S01 and display only their IDs.",
"Count completed and cancelled orders separately without using Python loops.",
"Create a five-row customer DataFrame with an explicit string schema.",
"Rename status to order_status without altering the source DataFrame.",
"Find the distinct channel values and explain why the result is small.",
"Compare show(3), take(3), and collect() on a five-row fixture.",
"Set the session timezone to UTC and verify the configuration value.",
"Predict how many actions run when the same filtered DataFrame is counted twice.",
"Explain why reading 300 rows locally does not demonstrate cluster scalability.",
"Reproduce an unresolved-column error and explain its message.",
"Explain why DataFrame rows have no guaranteed order unless explicitly sorted.",
"Show that withColumn returns a new DataFrame rather than mutating the original.",
"Design a safe inspection strategy for a billion-row orders table.",
"Compare where SparkSession objects and distributed row data live.",
"Identify driver-side Python code and distributed work in your solution.",
"Predict when a missing input path fails: during read construction or an action; verify.",
"Write a reusable session factory and a five-row smoke-check script."],
2: [
"Why can schema inference be risky for customer and product identifiers?",
"What do StructType and StructField represent?",
"What does nullable mean in a Spark schema?",
"Which type should represent quantity, and why?",
"Why use a decimal type for retail prices?",
"How do DateType and TimestampType differ?",
"What does the CSV header option control?",
"What is the difference between a blank field and a quoted empty string?",
"What does PERMISSIVE parsing attempt to preserve?",
"Why do file streams normally require an explicit schema?",
"Define and use a complete schema for customers.csv.",
"Define a complete order_items schema with decimal prices and discounts.",
"Read orders with order_ts parsed as a timestamp in UTC.",
"Compare inferred and explicit schemas for the same CSV file.",
"Read a CSV fixture containing a quoted comma in a customer name.",
"Read a header-only CSV with an explicit schema and verify zero rows.",
"Create a malformed numeric fixture and inspect PERMISSIVE output.",
"Compare DROPMALFORMED and FAILFAST on that fixture using an action.",
"Add source filename and ingestion timestamp audit columns.",
"Read one event archive file using the supplied nested event_schema.",
"Preserve malformed CSV evidence using a configured corrupt-record column.",
"Explain why fewer or extra CSV tokens are not always classified as corrupt records.",
"Demonstrate how column pruning can affect CSV corruption detection.",
"Compare missing columns, reordered columns, and incompatible types during ingestion.",
"Design a contract that distinguishes parsing failures from business-rule failures.",
"Explain why nullable=False is not a complete data-quality enforcement strategy.",
"Preserve an identifier with leading zeros through read and write.",
"Create a decimal-overflow fixture and record parsing behavior under your configuration.",
"Design ingestion that retains raw text for rows that cannot be typed safely.",
"Write a reusable reader with schema, format, audit columns, and parse-mode arguments."],
3: [
"How does select differ from withColumn?",
"How do you refer to a column using functions.col?",
"What does cast change about a column?",
"Why must CSV quantity be typed before arithmetic?",
"How do filter and where relate?",
"How do you combine column conditions using & and |?",
"Why are parentheses needed around combined comparisons?",
"What does when(...).otherwise(...) express?",
"How does isNull differ from comparing a column to None?",
"How are line gross and line net defined in this course?",
"Calculate net value for quantity 2, price 500, and discount 0.10.",
"Create decimal quantity-price-discount calculations for all line items.",
"Round line net to two decimal places using the course rounding rule.",
"Filter positive quantities with discount_pct between zero and one inclusive.",
"Classify amounts below 500, below 2000, and all remaining amounts.",
"Find lines with net amount greater than 2000.",
"Select only line_id and computed amounts without modifying raw columns.",
"Create fixtures for discounts 0, 1, -0.1, and 1.1.",
"Compare filtering null quantities with isNull and a numeric comparison.",
"Create a named reusable expression for net line amount.",
"Compare rounding each line before aggregation with rounding only the final total.",
"Demonstrate half-up rounding and explain how bround differs on a tie.",
"Create an overflow fixture and document behavior with ANSI mode enabled and disabled.",
"Explain the precision and scale of intermediate decimal multiplication.",
"Handle null price and discount explicitly without silently treating them as zero.",
"Test classification at 499.99, 500.00, 1999.99, and 2000.00.",
"Explain why a negative quantity must not become a negative sale in this dataset.",
"Compare built-in column expressions with a Python loop over collected rows.",
"Inspect whether chained projections are simplified in the optimized plan.",
"Write a calculation function and expected-output checks for all boundary cases."],
4: [
"What is a quarantine dataset used for?",
"How does a parse error differ from an invalid business value?",
"Why normalize email and city values?",
"What do trim and lower do?",
"What does coalesce return when several columns are null?",
"Why is a missing email allowed but a missing line_id rejected?",
"What is a referential-integrity violation?",
"Why retain more than one rejection reason per row?",
"What is the accepted-row grain before deduplication?",
"Why preserve original values alongside cleaned values?",
"Normalize customer email and city without changing IDs.",
"Flag null and blank line_id values using a tiny fixture.",
"Reject nonpositive quantities and negative prices.",
"Reject missing discounts and values outside the inclusive valid range.",
"Find unknown product IDs with a left anti join.",
"Find unknown order IDs independently of product validation.",
"Build an array containing every applicable rejection reason.",
"Write accepted and quarantined rows to separate Parquet paths.",
"Produce rejected-row counts for each rule.",
"Verify that raw rows equal accepted-before-dedup plus quarantined rows.",
"Create a row violating quantity, price, and product rules simultaneously.",
"Explain why summing per-rule rejection counts can exceed the quarantine row count.",
"Design mutually exclusive severity categories without losing detailed reasons.",
"Detect text that failed numeric casting rather than confusing it with original null.",
"Explain how SQL three-valued logic can accidentally admit invalid rows.",
"Test all-valid, all-invalid, and empty input DataFrames.",
"Preserve source-file metadata so a quarantined line can be traced to its origin.",
"Define a maximum rejection threshold and a pipeline failure policy.",
"Design a correction-and-reprocessing workflow that preserves the original audit.",
"Implement a reusable validator returning accepted rows, quarantine rows, and metrics."],
5: [
"What is the difference between a business key and an entire-row duplicate?",
"Why is order_id not unique in order_items?",
"What is the business key of an order line?",
"How does distinct differ from dropDuplicates on selected columns?",
"Why must cleaning happen before canonical line deduplication?",
"What makes a deduplication rule deterministic?",
"What does row_number assign within a window partition?",
"Why does a timestamp alone sometimes fail as a tie-break?",
"Why preserve removed duplicate rows?",
"When might two rows with one line_id represent a correction rather than an exact duplicate?",
"Count exact duplicate raw line rows.",
"Find line_id values appearing more than once.",
"Verify that supplied valid duplicate additions total eight rows.",
"Keep one accepted row per line_id and verify uniqueness.",
"Compare distinct with dropDuplicates(['order_id']) and explain the lost lines.",
"Build a fixture with two different lines belonging to one order.",
"Create a changed duplicate with a newer updated_at value.",
"Choose the newest correction using a window and stable tie-break.",
"Save discarded rows with the winning line_id for audit.",
"Check raw = quarantine + removed duplicates + clean unique lines.",
"Create equal-timestamp corrections and define a business-approved tie-break.",
"Explain why arbitrary dropDuplicates cannot guarantee the latest record.",
"Compare row-number winners after repartitioning the same fixture.",
"Design a duplicate policy when no trustworthy ordering metadata exists.",
"Distinguish missing-key rejection from deduplicating several null keys together.",
"Test idempotence: deduplicating an already deduplicated table changes nothing.",
"Explain why line_id and order_id+product_id are not interchangeable keys.",
"Design an audit that separates exact duplicates from conflicting corrections.",
"Compare batch permanent uniqueness with bounded streaming deduplication conceptually.",
"Write a configurable deduplication function and conflicting-record tests."],
6: [
"What does groupBy define about an aggregation's output grain?",
"How do count and countDistinct differ?",
"How does count(column) treat null values?",
"Why should AOV use orders rather than lines as its denominator?",
"Which order status contributes to booked revenue?",
"What is cancellation rate's denominator?",
"What does sum do when all values are null?",
"Why can revenue share be different from order-count share?",
"When should an undefined ratio be null rather than zero?",
"Why aggregate lines to order grain before calculating order averages?",
"Sum clean line_net by order_id.",
"Calculate booked revenue for completed orders only.",
"Compute store revenue and distinct completed-order counts.",
"Calculate store AOV from revenue and completed-order count.",
"Calculate cancellation rate at order grain.",
"Compute channel revenue shares and verify their total.",
"Count orders containing more than three accepted lines.",
"Find the highest-revenue product by units and by money.",
"Use conditional aggregation for completed and cancelled order counts.",
"Reconcile summed store revenue with global booked revenue.",
"Create a store with no completed orders and define its output metrics.",
"Explain why averaging store AOV values does not produce global AOV.",
"Reconstruct global AOV using correctly weighted store metrics.",
"Compare count(*) and count(customer_id) on a null-containing fixture.",
"Show how joining order totals back to lines can duplicate order-level revenue.",
"Define how an order with all lines rejected affects AOV and quality metrics.",
"Compare approximate distinct counting with exact counts for financial reporting.",
"Design a revenue reconciliation with decimal precision rather than floating tolerance.",
"Inspect the shuffle introduced by grouping and explain its key distribution.",
"Write a metric-definition document and independent fixture checks."],
7: [
"Who is the intended consumer of the sales report?",
"Which raw tables are required to compute booked revenue?",
"What is the output grain of the store report?",
"What is the output grain of the product report?",
"Why must cancelled orders be excluded from booked revenue?",
"What cleaning evidence should accompany a sales report?",
"Why should an input path be configurable?",
"What makes a report rerun reproducible?",
"Why keep monetary outputs in Parquet rather than only screenshots?",
"What business assumption must the report disclose about tax and shipping?",
"Assemble ingestion, cleaning, deduplication, and aggregation into one script.",
"Publish revenue and AOV by store.",
"Publish revenue and revenue share by channel.",
"Publish the top ten products by booked revenue.",
"Publish raw, quarantined, removed-duplicate, and accepted counts.",
"Verify booked revenue equals the manifest's expected amount.",
"Write a short explanation of the best-performing store.",
"Compare top products by units against top products by revenue.",
"Rerun the script with the same inputs and compare business rows.",
"Trace one BAD line from raw input to its quarantine reason.",
"Add a store with no sales without excluding it from the store report.",
"Test that an injected cancelled high-value order never increases booked revenue.",
"Test that an identical duplicate line never increases booked revenue.",
"Design behavior when every input line is rejected.",
"Demonstrate a failure caused by a missing product dimension key.",
"Make ranking deterministic when two products have equal revenue.",
"Explain whether two Parquet directories must be byte-identical to represent equal reports.",
"Design a report-level contract covering schema, grain, and totals.",
"Estimate what changes are needed to run the report over a year of large data.",
"Prepare a five-minute walkthrough with reproducible commands and reconciliation evidence."],
8: [
"What is a join key in the retail dataset?",
"How does an inner join differ from a left join?",
"When would you use a full outer join?",
"What does a left semi join return?",
"What does a left anti join return?",
"Why use aliases when column names overlap?",
"What is a many-to-one join?",
"What is join cardinality, and why does it affect revenue?",
"How do ordinary equality joins treat null keys?",
"Why check dimension-key uniqueness before enrichment?",
"Join clean lines to product attributes.",
"Join lines to order status and timestamp.",
"Join orders to customers and stores with explicit output columns.",
"Find unknown product references with a left anti join.",
"Find customers with completed orders using a left semi join.",
"Find customers without orders using a left anti join.",
"Find products never referenced by accepted lines.",
"Compare inner and left join results for a P999 fixture.",
"Verify that dimension enrichment preserves clean line count.",
"Select unambiguous column names after joining customers and stores.",
"Duplicate one product-dimension key and quantify revenue inflation.",
"Create a many-to-many fixture and predict its output row count.",
"Compare joining on a list of key names with an explicit equality condition.",
"Demonstrate null-safe equality on a tiny nullable-key fixture.",
"Explain why filtering the right-side column after a left join can remove unmatched rows.",
"Compare filtering right-side rows before a join with filtering joined output.",
"Design a strategy for unmatched keys: reject, preserve, or map to an unknown dimension.",
"Inspect physical join operators and identify a potential shuffle.",
"Test that revenue and row count are preserved after every intended many-to-one join.",
"Write an enrichment function that fails when a dimension key is duplicated."],
9: [
"What is a temporary view, and how long does it exist?",
"How do you register a DataFrame as a SQL view?",
"What is a SQL common table expression?",
"How does WHERE differ from HAVING?",
"What does CASE WHEN represent?",
"How does SQL treat comparisons with NULL?",
"Why should SQL reports select explicit columns?",
"What does ORDER BY guarantee about displayed results?",
"How do DataFrame and SQL operations use Spark's query engine?",
"What is the difference between an aggregate query and a row filter?",
"Write category revenue SQL over enriched completed lines.",
"Write its equivalent DataFrame transformation.",
"Use a CTE to compute order totals.",
"Find orders whose value exceeds the average completed-order value.",
"Use CASE WHEN to create basket bands.",
"Use HAVING to retain categories with revenue above a chosen threshold.",
"Find repeat customers using SQL distinct order counts.",
"Find products never sold using NOT EXISTS or an anti join.",
"Query cancelled-order rates by channel with an explicit denominator.",
"Compare ordered SQL and DataFrame results on a fixture.",
"Show how NOT IN with a null-containing subquery can produce surprising output.",
"Replace an unsafe NOT IN query with a correctly defined NOT EXISTS query.",
"Use EXPLAIN to compare SQL and DataFrame physical plans.",
"Explain why equivalent SQL strings may have different logical plans before optimization.",
"Create a correlated-subquery example and verify support in the pinned Spark version.",
"Avoid double-counting order totals when SQL joins order and line grains.",
"Demonstrate SQL three-valued logic with true, false, and null predicates.",
"Parameterize a date filter without inserting untrusted text into SQL expressions.",
"Design equality checks that handle nulls, decimals, and duplicate rows.",
"Write a SQL report with three CTEs and document each intermediate grain."],
10: [
"How does a window calculation differ from groupBy aggregation?",
"What does partitionBy mean inside a Window specification?",
"What does orderBy determine within a window?",
"How do row_number, rank, and dense_rank differ?",
"What does lag return for the first row in a partition?",
"What does lead return for the last row in a partition?",
"What is a cumulative sum?",
"What is a window frame?",
"Why use a stable secondary sort key?",
"Why should customer purchase ranking use orders rather than lines?",
"Rank products by revenue within each category.",
"Return exactly three products per category using row_number.",
"Return all tied third-place products using a documented rank rule.",
"Calculate running daily revenue per store.",
"Calculate day-over-day revenue differences with lag.",
"Find each customer's first and second completed order dates.",
"Identify the previous order value for each customer.",
"Calculate a three-row moving average on a tiny daily-sales fixture.",
"Build a fixture with tied revenues and compare all ranking functions.",
"Verify window calculations against hand-computed expected rows.",
"Compare ROWS and RANGE frames when two rows share the same date.",
"Explain why a three-row average is not necessarily a three-calendar-day average.",
"Densify the calendar before calculating a seven-day moving average.",
"Handle division by zero in percentage day-over-day changes.",
"Find gaps between purchases and flag customers returning after thirty days.",
"Explain the sorting and partitioning cost of multiple incompatible windows.",
"Predict behavior when a window has no partitionBy on a large dataset.",
"Test rankings after repartitioning to confirm deterministic tie handling.",
"Calculate each product's share of category revenue without reducing row count.",
"Build a reusable ranking report with tie-policy and frame-boundary tests."],
11: [
"Why distinguish a timestamp from a date?",
"What does the session timezone affect?",
"How does to_timestamp differ from to_date?",
"What does date_trunc return for a month?",
"How does datediff calculate elapsed days?",
"What is a calendar dimension?",
"Why can missing dates distort rolling averages?",
"What is a customer purchase cohort?",
"What is the denominator of cohort retention?",
"Why exclude customers without purchases from purchase cohorts?",
"Parse order_ts and derive order_date in UTC.",
"Calculate daily and monthly completed-order revenue.",
"Generate a date calendar covering the full sales period.",
"Build store-date combinations and fill missing sales with zero.",
"Find each customer's first completed purchase month.",
"Calculate month-0 cohort customer counts.",
"Calculate month-1 retained customer counts.",
"Calculate retention percentages with distinct customers.",
"Convert a 23:59 UTC fixture to Asia/Kolkata and compare dates.",
"Verify that month-0 retention is 100% for every nonempty cohort.",
"Calculate month offsets across a December-to-January boundary.",
"Explain why months_between can be inappropriate for integer cohort offsets.",
"Distinguish a true zero-sales day from a day whose ingestion failed.",
"Handle incomplete recent cohorts without interpreting unobserved months as churn.",
"Test leap-day and month-end date calculations on synthetic fixtures.",
"Compare week definitions at year boundaries and state the chosen convention.",
"Calculate a seven-calendar-day rolling revenue after calendar densification.",
"Define retention when a customer buys multiple times in the same month.",
"Build an as-of-date parameter so cohort outputs remain reproducible.",
"Publish a cohort matrix with observed-versus-unobserved cells distinguished."],
12: [
"What is a struct column?",
"What is an array column?",
"What is a map column?",
"How do you access a nested struct field?",
"How do you retrieve a value from a map?",
"What does explode do to row count?",
"How does explode_outer treat empty or null arrays?",
"What does from_json require besides a JSON string?",
"Why preserve event_id when flattening items?",
"How is an empty purchase basket different from a valid view event?",
"Read batch_001.json using the explicit nested schema.",
"Select event_id and device.os without flattening other fields.",
"Extract campaign from the attributes map.",
"Explode purchase items into one row per event item.",
"Calculate item amount from nested quantity and price.",
"Count items per event before and after flattening.",
"Use a higher-order function to calculate basket quantities.",
"Create empty-array and null-array fixtures and compare explode variants.",
"Reconstruct an items array from flattened rows using a documented ordering key.",
"Identify malformed or empty purchase events for quarantine.",
"Show why exploding two independent arrays can create a Cartesian multiplication.",
"Use arrays_zip for paired arrays and define behavior for unequal lengths.",
"Preserve item position with posexplode when order matters.",
"Compare higher-order expressions with a Python UDF for array calculations.",
"Parse JSON missing a nested field and record the resulting null behavior.",
"Handle an unknown map key without replacing valid values.",
"Validate each item rather than only checking that the basket array exists.",
"Create one basket containing both valid and invalid items and define rejection policy.",
"Compare event-level and item-level counts to avoid inflated purchase metrics.",
"Write a flattening function with fixtures for null, empty, and multiple-item baskets."],
13: [
"What is a built-in Spark column expression?",
"What is a Python UDF?",
"What must a Python UDF declare about its output?",
"Why can Python serialization affect UDF performance?",
"What is a pandas UDF intended to process?",
"What role does Arrow play in data transfer?",
"Why prefer built-ins for common string and numeric operations?",
"How should basket bands handle null amounts?",
"Why must benchmarks include an action?",
"Why are compatible pandas and Arrow versions important?",
"Implement basket bands using when expressions.",
"Implement an equivalent ordinary Python UDF.",
"Check bands for 499.99, 500, 1999.99, and 2000.",
"Check null amounts in both implementations.",
"Normalize emails with built-ins and compare with a Python implementation.",
"Inspect plans for built-in and Python UDF versions.",
"Benchmark both implementations on the same scaled input.",
"Repeat timings three times after an initial warm-up.",
"Optionally implement a pandas UDF in a compatible separate environment.",
"Document dependency versions and action results for every benchmark.",
"Explain why a count action may prune a computed UDF column from execution.",
"Choose an action that forces evaluation of the benchmarked output column.",
"Reproduce a null-handling UDF error and repair it.",
"Explain why nondeterministic UDFs need explicit care in repeated computations.",
"Compare row-at-a-time Python UDFs with vectorized pandas UDFs.",
"Explain why vectorization does not remove every serialization or memory cost.",
"Avoid external network calls inside a per-row UDF; propose a join-based alternative.",
"Test return-type mismatches and document observed behavior.",
"Design a UDF review checklist covering types, nulls, determinism, and dependency distribution.",
"Replace a complex UDF with composable built-ins and compare correctness and plans."],
14: [
"What is the grain of fact_order?",
"What is the grain of fact_line?",
"What does a dimension table add to a fact table?",
"What do recency, frequency, and monetary represent?",
"Why fix an as-of date for RFM analysis?",
"Why should frequency count distinct orders?",
"Which statuses are included in customer monetary value?",
"How should customers without completed purchases appear?",
"What is the grain of a cohort retention result?",
"Why keep category preferences separate from customer-level RFM?",
"Build a unique fact_order table with completed-order totals.",
"Build a unique fact_line table with product and order keys.",
"Validate all dimension keys before mart joins.",
"Calculate recency as of 2026-10-01.",
"Calculate completed-order frequency and booked monetary value.",
"Define transparent RFM bands using documented thresholds.",
"Create customer segments from those bands.",
"Calculate each customer's highest-revenue category.",
"Publish month-0 and month-1 retention from purchase cohorts.",
"Reconcile mart monetary totals with Project 1 revenue.",
"Test a customer with only cancelled orders.",
"Test a customer with three lines in one completed order.",
"Resolve category-preference ties with a deterministic rule.",
"Compare fixed bands with quantile-based RFM bands and explain small-sample limitations.",
"Explain why customer-level monetary values inflate when joined repeatedly to line facts.",
"Add a dimension attribute and prove it does not change facts or totals.",
"Design separate semantics for return-adjusted monetary value.",
"Create a customer-segment change report across two as-of dates.",
"Design a mart contract covering key uniqueness and time definitions.",
"Prepare a customer-analysis walkthrough with fixtures and exact reconciliation."],
15: [
"What is columnar storage?",
"How does Parquet differ from CSV?",
"What does directory partitioning encode?",
"What is partition pruning?",
"Why can high-cardinality partition keys cause problems?",
"What is a small-file problem?",
"How do repartition and coalesce differ?",
"What does overwrite mode do at an output path?",
"What is the difference between a managed and an external table?",
"Why is order_date a plausible retail partition column?",
"Write clean facts as Parquet partitioned by order_date.",
"Read one date and verify its rows against a full-data filter.",
"Inspect PartitionFilters in an explain plan.",
"Compare CSV and Parquet schema preservation.",
"Compare output sizes and file counts for both formats.",
"Create a SQL view over a Parquet path.",
"Write a scratch dataset with coalesce(1) and inspect file count.",
"Compare compression settings on the same scratch dataset.",
"List how many files were written per date partition.",
"Demonstrate overwrite behavior only on disposable scratch data.",
"Explain why partitioning by customer_id can produce too many directories.",
"Distinguish partition pruning from Parquet predicate pushdown.",
"Compare selecting two columns with reading every column in the plan.",
"Design a compaction strategy for many tiny daily files.",
"Explain why coalesce(1) can bottleneck a large output.",
"Compare static and dynamic partition overwrite on an isolated fixture.",
"Document how appending incompatible schemas should be prevented.",
"Design retention and backfill boundaries for a partitioned fact table.",
"Compare directory partitions with runtime execution partitions.",
"Propose a file layout for one year of retail data with daily reporting needs."],
16: [
"What is a logical query plan?",
"What is a physical query plan?",
"What does Catalyst optimize?",
"What is a Spark job?",
"What is a Spark stage?",
"What is a task?",
"What is a shuffle?",
"How do narrow and wide transformations differ?",
"Why does an action trigger distributed execution?",
"What information does the Spark UI provide?",
"Save explain('formatted') output for a filtered scan.",
"Save a physical plan for a grouped revenue query.",
"Identify exchange operators in an aggregation plan.",
"Inspect a join plan and identify its join operator.",
"Compare plans before and after selecting only required columns.",
"Run an action and inspect its jobs and stages in the UI.",
"Compare global orderBy with sortWithinPartitions.",
"Inspect the number of partitions before and after repartition.",
"Identify scan filters and projected columns in a Parquet plan.",
"Annotate a plan with scan, filter, exchange, join, and aggregation nodes.",
"Explain how partial aggregation reduces shuffle data volume.",
"Distinguish the initial and final adaptive execution plans.",
"Explain why a single action can create several jobs.",
"Trace why repeated uncached actions can recompute the same transformations.",
"Compare a broadcast exchange with a shuffle exchange.",
"Identify a potential single-partition bottleneck in a window query.",
"Explain driver-memory risk in collecting a large aggregation result.",
"Predict which operations in a multi-step pipeline cause shuffles and verify.",
"Diagnose a slow stage using task duration, input size, and spill metrics.",
"Write a plan-based optimization note with evidence rather than guessed speedups."],
17: [
"What is a broadcast join?",
"When is broadcasting a dimension reasonable?",
"What is Adaptive Query Execution?",
"What is data skew?",
"What does persist retain for reuse?",
"Why call unpersist after repeated work?",
"Why can too many shuffle partitions hurt tiny workloads?",
"How does coalesce differ from a full repartition shuffle?",
"Why should benchmark results include input size?",
"Why do local timings not directly predict cluster performance?",
"Generate at least 100000 synthetic lines with unique IDs.",
"Join a small product dimension using an explicit broadcast hint.",
"Compare its plan with a non-broadcast join plan.",
"Benchmark repeated aggregations without caching.",
"Cache the reused input, materialize it, and repeat the benchmark.",
"Unpersist cached input and verify your cleanup code runs.",
"Create a hot product key holding most rows.",
"Measure row counts per partition for the skewed dataset.",
"Compare three shuffle partition settings on identical inputs.",
"Record median action-based runtimes over three measured runs.",
"Salt a skewed aggregation and recombine partial totals correctly.",
"Explain why salting a join requires careful duplication or mapping of the other side.",
"Test that optimization preserves exact revenue and business keys.",
"Inspect AQE settings and compare initial versus final join choices.",
"Explain broadcast memory costs on the driver and executors.",
"Compare cache benefits when an input is reused once versus five times.",
"Prevent a benchmark action from pruning the computation being measured.",
"Diagnose whether long tasks indicate skew, spill, or expensive per-row logic.",
"Design a larger benchmark that separates read time from transformation time.",
"Produce a performance report with correctness checks, settings, and limitations."],
18: [
"What is a data contract?",
"What is the purpose of a small deterministic fixture?",
"How does a unit test differ from an integration test?",
"Why is equal row count insufficient to prove equal output?",
"What should a schema assertion check?",
"Why test null inputs explicitly?",
"What is a negative test?",
"Why should tests avoid relying on unspecified row order?",
"What does assertDataFrameEqual help compare?",
"What is a quality threshold used for?",
"Test the 900.00 net amount calculation using explicit decimal types.",
"Test every basket-band boundary.",
"Test null and blank key rejection.",
"Test discount values below zero and above one.",
"Test unknown product and order references.",
"Test that dimension enrichment preserves line count.",
"Test that line business keys are unique after deduplication.",
"Test that cancelled orders do not increase booked revenue.",
"Test empty input and all-invalid input.",
"Create a contract for required columns, types, keys, and statuses.",
"Introduce a faulty rounding implementation and show that a test detects it.",
"Introduce an extra dimension row and detect join inflation.",
"Test changed duplicates with equal timestamps and deterministic tie-breaks.",
"Compare schema checks with value-level business validation.",
"Design property checks for revenue additivity across disjoint partitions.",
"Test transformation idempotence where business semantics require it.",
"Explain when approximate floating equality is appropriate and when decimals are required.",
"Keep tests isolated so temporary views and output paths do not interfere.",
"Design a small integration test covering raw-to-gold reconciliation.",
"Create a test report showing each deliberately broken implementation was caught."],
19: [
"What is incremental batch ingestion?",
"How does ingestion time differ from business event time?",
"What is an ingestion high-water mark?",
"How is a batch high-water mark different from a streaming event-time watermark?",
"What does SCD Type 1 retain?",
"What does SCD Type 2 retain?",
"What do valid_from and valid_to represent?",
"Why use half-open validity intervals?",
"What makes an incremental load idempotent?",
"Why does plain Parquet not provide a native transactional MERGE?",
"Split orders into two input arrival batches.",
"Add batch_id and ingested_at metadata.",
"Create a customer city update with a newer update timestamp.",
"Build a latest-row SCD1 customer snapshot.",
"Build two SCD2 versions for a changing customer.",
"Join an order to the customer version valid at order time.",
"Detect overlapping validity intervals for the same customer.",
"Create a committed-input manifest for processed batch IDs.",
"Retry the same input batch and verify no duplicate business rows.",
"Publish a small complete snapshot after validation rather than assuming Parquet upserts.",
"Handle a late order whose business date precedes the latest ingestion timestamp.",
"Explain why filtering solely on max(order_ts) can miss late-arriving records.",
"Create an out-of-order dimension update and rebuild valid intervals correctly.",
"Handle two customer updates with the same timestamp using a documented policy.",
"Model a customer deletion or inactive status without deleting historical facts.",
"Design recovery when output is staged but the batch manifest is not committed.",
"Compare SCD2 business history with system ingestion history.",
"Explain the transaction guarantees that Delta, Iceberg, or Hudi can add.",
"Define a backfill strategy that updates historical partitions safely.",
"Write an incremental-load design with retry, late-data, and concurrent-writer assumptions."],
20: [
"What belongs in bronze, silver, and gold layers?",
"Why retain raw bronze records?",
"What is the purpose of a run_id?",
"Which quality metrics should a batch run log?",
"Why aggregate return events before joining sales lines?",
"Why deduplicate return_id before summing returned quantities?",
"Which returns are valid under the course business rules?",
"Why should staging outputs be validated before publication?",
"What information belongs in a recovery runbook?",
"Why is local folder publication not a distributed transaction?",
"Build a CLI accepting input, output, and run-id arguments.",
"Write separate bronze, validated silver, and reporting gold outputs.",
"Record raw, rejected, duplicate, and accepted line counts.",
"Aggregate accepted return units by line_id.",
"Calculate return deductions and return-adjusted revenue.",
"Reconcile return-adjusted revenue with the manifest.",
"Reject a return referencing an unknown line.",
"Reject return quantities exceeding the line's purchased units.",
"Run the same input twice and compare unique business rows.",
"Document a complete initial-load command and expected outputs.",
"Inject a failure after staging and demonstrate a safe recovery run.",
"Inject failure after publication but before run-status recording and discuss retry handling.",
"Test multiple partial returns against one sale without revenue multiplication.",
"Define how invalid return records affect pipeline status and reporting.",
"Design atomic publication assumptions for local storage versus object storage.",
"Define a policy for two runs trying to publish the same output concurrently.",
"Separate financial metric failures from noncritical missing-email warnings.",
"Design partition-specific backfills with unaffected dates preserved.",
"Package transformation functions and meaningful integration checks.",
"Deliver an operations walkthrough covering success, validation failure, crash, and retry."],
21: [
"What is an RDD?",
"How does an RDD differ from a DataFrame?",
"What does RDD map return?",
"How does flatMap differ from map?",
"What is a key-value pair RDD?",
"What does reduceByKey compute?",
"What is a broadcast variable used for?",
"What is an accumulator used for?",
"Why is the DataFrame API usually preferred for structured retail data?",
"Why is the JVM typed Dataset API not a Python DataFrame feature?",
"Convert a tiny product-quantity DataFrame to a pair RDD.",
"Sum quantities by product using reduceByKey.",
"Compute the same totals with DataFrame groupBy.",
"Compare RDD and DataFrame totals after deterministic sorting.",
"Build a word count over product names using flatMap.",
"Broadcast a tiny product-category dictionary for an RDD lookup.",
"Use mapPartitions for a partition-level diagnostic.",
"Add an accumulator for a nonfinancial diagnostic counter.",
"Inspect RDD partition counts and lineage.",
"Write a short comparison of DataFrames, pandas API on Spark, and Spark Connect.",
"Compare groupByKey and reduceByKey shuffle behavior for summation.",
"Explain the associativity and commutativity assumptions of distributed reductions.",
"Show why floating-point reductions can vary with reduction order.",
"Explain how task retries or repeated actions can make accumulator totals unsuitable for revenue.",
"Distinguish a Spark broadcast variable from a SQL broadcast join hint.",
"Explain serialization risks when an RDD closure captures a large Python object.",
"Compare partition-wise initialization with per-row initialization of a lookup resource.",
"Explain why Spark Connect does not expose every classic RDD/SparkContext workflow.",
"Design a decision rule for choosing DataFrame expressions over custom RDD logic.",
"Produce a small equivalent RDD/DataFrame implementation with correctness and API tradeoffs."],
22: [
"What makes a DataFrame streaming rather than bounded?",
"What is a micro-batch?",
"How does readStream differ from read?",
"What is a streaming source?",
"What is a streaming sink?",
"What is a checkpoint directory used for?",
"What does append output mode mean for a stateless query?",
"What does maxFilesPerTrigger control?",
"Why must arriving files be complete and immutable?",
"What does a processingTime trigger configure?",
"Start the supplied stream with an empty input directory.",
"Publish batch_001.json atomically with the publisher script.",
"Read the generated Parquet sink and inspect its events.",
"Publish batch_002.json while the query is running.",
"Inspect isStreaming on the input DataFrame.",
"Save query.lastProgress after a processed batch.",
"Stop and restart the same query with its existing checkpoint.",
"Verify committed source files are not processed again after restart.",
"Run an availableNow query on a separate set of paths.",
"Compare batch and stream ingestion schemas for identical JSON.",
"Explain why committed-file recovery does not remove duplicate business event IDs.",
"Publish a new filename containing an already-seen event and observe the duplicate.",
"Explain why modifying an already-discovered file is an invalid replay strategy.",
"Distinguish processingTime trigger intervals from guaranteed processing latency.",
"Explain why availableNow is different from a continuous listener.",
"Design isolated input, output, and checkpoint paths for repeatable tests.",
"Compare restarting with a retained checkpoint versus starting a fresh query.",
"Explain what Spark and the sink each contribute to recovery guarantees.",
"Create an ingestion runbook for empty input, malformed input, and interrupted processing.",
"Build a controlled two-batch smoke test with saved counts and progress evidence."],
23: [
"What is event time?",
"What is processing time?",
"What is a tumbling event-time window?",
"What is a sliding window?",
"What does withWatermark declare?",
"Why must event_time be parsed as a timestamp?",
"What state does a windowed count retain?",
"How do append and update modes differ for aggregations?",
"Why might a finalized window not appear immediately?",
"Why is a watermark not a fixed wall-clock lateness cutoff?",
"Count purchase events in five-minute event-time windows.",
"Add a ten-minute event-time watermark before aggregation.",
"Publish batches in order, waiting for each to finish.",
"Save eventTime watermark values from query progress.",
"Compare a controlled on-time and six-minute-late event.",
"Publish a much older event after advancing event time.",
"Compare five-minute tumbling windows with ten-minute windows sliding every five minutes.",
"Test events exactly at 10:00, 10:04:59, and 10:05 window boundaries.",
"Run separate append and update experiments with separate checkpoints.",
"Inspect retained-state and dropped-by-watermark metrics where available.",
"Explain why newer data and a subsequent micro-batch can be needed for final output.",
"Predict windows receiving one event in a sliding-window query.",
"Explain why summing sliding-window counts double-counts events across overlapping windows.",
"Test a future-dated outlier and discuss its effect on watermark advancement.",
"Explain the guarantee for within-delay data versus possible dropping beyond the delay.",
"Compare watermark placement before and after aggregation and verify supported usage.",
"Define a business policy for events arriving after finalization.",
"Estimate state size as a function of keys, windows, and delay threshold.",
"Design controlled late-data tests independent of real wall-clock waiting.",
"Publish a lateness report with event timestamps, arrival batches, watermarks, and observed outputs."],
24: [
"Why can a streaming source contain duplicate business events?",
"What is the event deduplication key?",
"What does dropDuplicatesWithinWatermark provide?",
"Why does bounded deduplication need event-time information?",
"How is bounded deduplication different from permanent uniqueness?",
"What is a stream-static join?",
"Why must the static product key be unique?",
"Why retain event_id after exploding purchase items?",
"How does purchase-event revenue differ from batch booked revenue?",
"What is dimension freshness in a streaming application?",
"Deduplicate event_id using the supplied ten-minute watermark.",
"Publish the repeated E0001 event within the tested delay horizon.",
"Verify the controlled duplicate is counted once.",
"Explode valid purchase items and enrich them with static product attributes.",
"Compute item amounts from event-supplied prices rather than current catalog prices.",
"Preserve unmatched product keys in an audit output.",
"Test static dimension duplication and its effect on streamed amounts.",
"Create an event with a known product and an unknown product.",
"Document the product snapshot loaded by the query.",
"Verify event-level purchase counts are not replaced by item counts.",
"Send the same event_id with a slightly different timestamp inside the horizon.",
"Advance event time, then test an old duplicate after state eviction.",
"Explain why deduplicating only event_id without a bound can grow state indefinitely.",
"Compare duplicate business events with duplicated file publication.",
"Define whether to reject or preserve conflicting payloads sharing an event_id.",
"Test invalid timestamps before stateful deduplication.",
"Design per-event basket calculations using higher-order functions without an unbounded event-id aggregation.",
"Change a static dimension and document whether the running query observes the change.",
"Propose a historical-price enrichment strategy for changing catalog data.",
"Write a deduplication contract stating horizon, key, conflict policy, and replay limitations."],
25: [
"What does foreachBatch pass to its callback?",
"What does batch_id identify?",
"Why can a foreachBatch callback execute again for a retried batch?",
"What makes a sink write idempotent?",
"Why are checkpoints necessary but insufficient for arbitrary external side effects?",
"What should a committed-batch record mean?",
"Why isolate query checkpoint directories?",
"Why can changing stateful query logic make recovery incompatible?",
"What is the difference between a source replay and a sink duplicate?",
"Why should a callback not collect a large batch to the driver?",
"Write each batch to a stable batch_id-specific Parquet path.",
"Log batch_id, row count, and output location.",
"Create a local committed-batch marker after successful publication.",
"Inject failure before the output is committed.",
"Restart and verify that retry produces one logical output batch.",
"Run two actions inside the callback and discuss temporary caching.",
"Record query progress before and after restart.",
"Verify an empty batch does not crash your callback.",
"Keep stateful logic unchanged during a checkpoint-recovery experiment.",
"Document the local-filesystem assumptions of your callback implementation.",
"Inject failure after writing but before recording success and analyze the duplicate risk.",
"Explain why check-then-write is insufficient with concurrent writers.",
"Design a transactional sink protocol that combines data publication and commit recording.",
"Explain why batch_id alone is not globally unique across unrelated queries.",
"Define a query identity plus batch_id key for sink commits.",
"Compare overwrite-per-batch lab outputs with append-only external side effects.",
"Design safe recovery after checkpoint loss without assuming source events remain retained.",
"Explain which query changes require a deliberate new checkpoint and replay plan.",
"Ensure a stateful foreachBatch consumer fully consumes the batch as required by the query.",
"Deliver a failure-matrix test covering pre-write, post-write, pre-commit, and restart behavior."],
26: [
"What is a Kafka topic?",
"What is a Kafka partition?",
"What is a record offset?",
"How do a record key and value differ?",
"Why does a Kafka key not automatically deduplicate events?",
"What are bootstrap servers used for?",
"Why is a Spark Kafka connector package needed?",
"What does startingOffsets='earliest' request for a fresh query?",
"How does a checkpoint affect offsets on restart?",
"What is a dead-letter or quarantine output?",
"Complete the equivalent file-source parse-and-quarantine lab first.",
"For the optional broker lab, create a retail-events topic.",
"Publish one archive event as a Kafka value.",
"Publish keyed events using event_id as the key.",
"Read Kafka topic, partition, offset, key, and value columns.",
"Parse value with from_json and the explicit event schema.",
"Preserve source metadata when flattening event fields.",
"Route a malformed JSON record into quarantine.",
"Restart from the same checkpoint and inspect resumed source progress.",
"Record connector coordinates, broker version, and observed event counts.",
"Explain why adding partitions affects ordering assumptions across keys.",
"Compare earliest, latest, and explicit offsets only on fresh isolated queries.",
"Explain how source retention can prevent checkpoint-based recovery.",
"Send duplicate keyed values and verify your Spark business deduplication.",
"Distinguish Kafka log ordering within a partition from global event-time ordering.",
"Design output event keys for downstream duplicate handling.",
"Explain why a Kafka sink can contain duplicates during retry.",
"Configure an ingestion-rate bound and observe its effect on lag.",
"Design offset-range evidence for replay and reconciliation without claiming Kafka consumer commits drive Spark recovery.",
"Write a broker-unavailable and retention-loss runbook; provide a file-source simulation if no broker is available."],
27: [
"What is a stream-stream join?",
"How does a stream-stream join differ from a stream-static join?",
"Why do streaming joins retain state?",
"What is a time-bounded join condition?",
"Why watermark both inputs in the bounded join lab?",
"What is a session window?",
"What does a ten-minute session gap mean?",
"Why can unmatched outer-join rows be delayed?",
"How does processing-order arrival differ from event-time matching?",
"What is the purpose of a state store?",
"Read purchase and payment events from independent input directories.",
"Parse and validate both event-time columns.",
"Join purchases and payments by order_id with the required fifteen-minute time bound.",
"Publish a matching purchase and payment fixture.",
"Publish a payment outside the matching event-time range.",
"Publish a payment before its purchase in processing order.",
"Inspect join state rows after successive batches.",
"Advance event time on both inputs and inspect cleanup behavior.",
"Build a separate customer session-window aggregation.",
"Test activity separated by gaps smaller and larger than ten minutes.",
"Explain how Spark's multiple-watermark policy affects a slow input.",
"Compare minimum and maximum watermark policies and their late-data tradeoffs.",
"Design a left outer join fixture demonstrating delayed unmatched output.",
"Explain why equality on order_id alone can allow unbounded state.",
"Predict a many-to-many output when an order has several payment events.",
"Design payment deduplication before joining without unsupported stateful chaining assumptions.",
"Explain session merging when a late event bridges two previously separate sessions.",
"Discuss RocksDB state-store benefits and deployment-specific memory considerations.",
"Sketch a custom per-customer state machine with a timeout and bounded-state policy.",
"Deliver independent join and session experiments with checkpoint paths and state-growth evidence."],
28: [
"What is a supervised learning label?",
"What is a feature?",
"What does VectorAssembler produce?",
"What is a Spark ML Pipeline?",
"What is a training set?",
"Why use a temporal split for daily retail demand?",
"What is target leakage?",
"What does MAE measure?",
"Why compare a model with a simple baseline?",
"Why are synthetic-data model results not proof of business value?",
"Aggregate daily units by store and category.",
"Fill missing calendar days with zero units where ingestion is complete.",
"Create yesterday's units as a lagged feature.",
"Split earlier dates for training and later dates for evaluation.",
"Build a yesterday-demand baseline.",
"Assemble numeric features into a vector.",
"Fit a LinearRegression model using training rows only.",
"Generate predictions for the evaluation dates.",
"Calculate baseline and model MAE on the same rows.",
"Save split dates, features, and model parameters in an experiment note.",
"Explain why random row splitting can leak future seasonality into evaluation.",
"Avoid including target-day sales totals in demand predictors.",
"Fit preprocessing on training data and explain why global fitting leaks information.",
"Design walk-forward evaluation across multiple time cutoffs.",
"Compare per-store MAE with global MAE to identify uneven performance.",
"Explain why MAPE is problematic when observed demand is zero.",
"Sketch a purchase-classification label with a prediction-time cutoff.",
"Sketch ALS user-item inputs and distinguish implicit feedback from explicit ratings.",
"Design cold-start behavior for unseen customers and products.",
"Deliver an experiment report including leakage checks, baseline results, and synthetic-data limitations."],
29: [
"Which components are needed for a live retail monitor?",
"What makes a streaming metric provisional?",
"Why validate events before computing business metrics?",
"Why deduplicate purchase events before calculating revenue?",
"What is an alert rule?",
"Why should alerts have a stable identity?",
"What does inputRowsPerSecond describe?",
"What does processedRowsPerSecond describe?",
"Why monitor watermark and state-row counts?",
"Why does absence of incoming events not automatically mean failure?",
"Build event ingestion with explicit schema and audit metadata.",
"Quarantine invalid timestamps and empty purchase baskets.",
"Deduplicate valid events within the defined delay horizon.",
"Enrich valid purchase items with a unique static dimension.",
"Produce five-minute purchase counts and event revenue.",
"Create a separate high-value-basket alert query.",
"Generate a basket above 10000 to test the alert path.",
"Save local alert records using event_id and rule version as identity.",
"Collect progress snapshots and input-to-output reconciliation counts.",
"Demonstrate stop-and-restart recovery with retained checkpoints.",
"Replay an alert-producing event and verify your defined duplicate behavior.",
"Compare provisional window output with finalized append output.",
"Create a delayed event and explain whether the metric or alert should change.",
"Design monitoring thresholds for lag, failures, state growth, and source silence.",
"Identify hot-key bottlenecks without changing monetary correctness.",
"Define alert sink idempotence independently from query checkpoint recovery.",
"Design a raw-event replay path for events excluded by the online lateness policy.",
"Document why batch booked revenue cannot be directly equated to simulated event revenue.",
"Separate metrics and alerts into compatible query plans with independent checkpoints.",
"Deliver a live-monitor runbook covering bad input, duplicates, late data, sink failure, and recovery."],
30: [
"What are the main layers of your final retail platform?",
"Which datasets are sources of truth for batch financial reports?",
"Which outputs serve customer analytics?",
"Which outputs serve live operational monitoring?",
"What does a data contract specify?",
"What is a recovery runbook?",
"Why separate finalized daily results from provisional streaming metrics?",
"What does spark-submit provide?",
"Why should runtime credentials remain outside source code?",
"Which limitations of the synthetic fixtures must the final project disclose?",
"Integrate the sales report, customer mart, return adjustments, and live monitor.",
"Create an architecture diagram with sources, transformations, state, and sinks.",
"Document every output grain and business key.",
"Publish exact batch revenue and return reconciliation evidence.",
"Map streamed purchase order_ids to batch orders and classify unmatched records.",
"Include the demand-model comparison with its chronological split and baseline.",
"Write reproducible initial-load and stream-start commands.",
"Demonstrate two arrival batches, a duplicate, a late event, and a restart.",
"Package meaningful tests and saved progress evidence.",
"Prepare a ten-minute walkthrough of the complete platform.",
"Design a historical backfill that does not corrupt current stream state or output.",
"Explain reconciliation differences caused by status, contents, timing, and returns.",
"Propose partition and file layouts for one million daily events.",
"Estimate bottlenecks from measured workload characteristics rather than guessing executor counts.",
"Define freshness, correctness, and recovery objectives for each output.",
"Design failure handling for source loss, corrupted checkpoint, and partial sink commits.",
"Compare a local Parquet publication design with a transactional production sink.",
"Define access controls and retention for customer fields and audit records.",
"Explain tradeoffs between latency, state size, replayability, and reporting finality.",
"Perform a final design review with test evidence, operational risks, and a prioritized improvement plan."],
}

def render_questions(day):
    questions = QUESTIONS[day]
    assert len(questions) == 30, (day, len(questions))
    headings = ['Foundation questions (1-10)', 'Hands-on questions (11-20)', 'Advanced challenges (21-30)']
    lines = ['## Daily question bank - 30 questions', '',
             'Solve in order: questions 1-10 establish the basics, 11-20 apply them to retail data, and 21-30 test edge cases, debugging, and design. Advanced questions are relative to this day; later days build on earlier work.', '',
             'Answer conceptual questions in your own words. For practical questions, submit executable code, a small input fixture, expected output, and observed results. Preserve question numbers in `answers.md`. Optional infrastructure questions may use the stated file-source alternative.', '']
    for group, heading in enumerate(headings):
        lines += ['### '+heading, '']
        for offset in range(10):
            num = group*10+offset+1
            lines.append(f'{num}. {questions[num-1]}')
        lines.append('')
    return '\n'.join(lines)
